/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavBar: typeof import('./src/components/layout/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNavBar: typeof import('./src/components/layout/SideNavBar.vue')['default']
    TopNavBar: typeof import('./src/components/layout/TopNavBar.vue')['default']
  }
}
