/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ArticleList: typeof import("./src/components/ArticleList.vue")["default"];
    Card: typeof import("./src/components/common/card.vue")["default"];
    ElAvatar: typeof import("element-plus/es")["ElAvatar"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDrawer: typeof import("element-plus/es")["ElDrawer"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElImage: typeof import("element-plus/es")["ElImage"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElPopover: typeof import("element-plus/es")["ElPopover"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    Emoji: typeof import("./src/components/common/emoji.vue")["default"];
    Footer: typeof import("./src/components/layout/Footer.vue")["default"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    IndexBack: typeof import("./src/components/layout/IndexBack.vue")["default"];
    Loader: typeof import("./src/components/common/loader.vue")["default"];
    MyAside: typeof import("./src/components/layout/MyAside.vue")["default"];
    MyFooter: typeof import("./src/components/common/myFooter.vue")["default"];
    Photo: typeof import("./src/components/common/photo.vue")["default"];
    Printer: typeof import("./src/components/common/printer.vue")["default"];
    ProButton: typeof import("./src/components/common/proButton.vue")["default"];
    Process: typeof import("./src/components/common/process.vue")["default"];
    ProPage: typeof import("./src/components/common/proPage.vue")["default"];
    ProTag: typeof import("./src/components/common/ProTag.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SideNavBar: typeof import("./src/components/layout/SideNavBar.vue")["default"];
    SvgIcon: typeof import("./src/components/common/SvgIcon.vue")["default"];
    TopNavBar: typeof import("./src/components/layout/TopNavBar.vue")["default"];
    TreeHole: typeof import("./src/components/common/treeHole.vue")["default"];
    TwoPoem: typeof import("./src/components/common/TwoPoem.vue")["default"];
    UploadPicture: typeof import("./src/components/common/uploadPicture.vue")["default"];
    Zombie: typeof import("./src/components/common/zombie.vue")["default"];
  }
}
