<template>
  <IndexBack></IndexBack>
  <div>home123</div>
  <div>home2</div>
  <div>home3</div>
  <div>home4</div>
  <div>home5</div>
  <div>home6</div>
  <div>home7</div>
  <div>home8</div>
  <div>home9</div>
  <div>home0</div>
  <div>home11</div>
  <div>home12</div>
  <div>home13</div>
  <div>home14</div>
  <div>home15</div>
  <div>home16</div>
  <div>home17</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
</template>

<script setup lang="ts"></script>

<style></style>
