<template>
  <IndexBack></IndexBack>
  <div>home123</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
  <div>home</div>
</template>

<script setup lang="ts"></script>

<style></style>
